//This constant stores the styles of all the elements of the Task Details Component
export const TaskDetailsStyles = {
  modal_wrapper: 'flex flex-row justify-between items-start gap-x-24 h-fit w-2/4 px-8 py-6 border-2 border-[#edecf1] bg-[#313237] backdrop-blur-md drop-shadow-[0_0_2px_#1A1A1A] rounded-md',
  modal: 'z-[9999] py-28 flex flex-wrap flex-row justify-center items-center fixed top-0 left-0 w-screen h-screen bg-[#1A1A1A]/20 backdrop-blur-sm',
  info_block: 'flex flex-wrap flex-col justify-start items-start gap-y-4',
  info_section_block: 'flex flex-wrap flex-col justify-end items-start gap-y-8 mt-4',
  requirements_wrapper: 'flex flex-wrap flex-col justify-start items-start gap-y-4 list-disc ml-4',
  main_info_wrapper: 'flex flex-wrap flex-col justify-start items-start gap-y-1.5',
  details_wrapper: 'flex flex-wrap flex-row justify-start items-center gap-x-6',
  info_section_wrapper: 'flex flex-wrap flex-col justify-end items-start gap-y-4',
  state_wrapper: 'flex flex-wrap flex-row justify-center items-center gap-x-1.5',
  stats_wrapper: 'flex flex-wrap flex-row justify-center items-center gap-x-12',
  date_wrapper: 'flex flex-wrap flex-col justify-start items-start gap-y-2',
  date_inner_wrapper: 'flex flex-wrap flex-row justify-start items-start gap-x-12',
  actions_wrapper: 'flex flex-col justify-start items-end gap-y-12 w-fit',
  buttons_wrapper: 'flex flex-col justify-start items-end gap-y-6',
  requirement: 'text-xs font-normal break-all text-[#BABABA]',
  text_title: 'break-words font-semibold text-xl',
  text_subtitle: 'text-md font-medium text-[#edecf1] tracking-wider',
  text_normal: 'text-xs font-normal break-all',
  text_basis: 'text-xs font-medium',
  text_gray: 'text-[#E0E0E0]',
  text_darkgray: 'text-[#BABABA]',
  button: 'text-xs font-medium cursor-pointer text-[#edecf1] bg-transparent hover:bg-[#ffffff]/10 hover:border-[#edecf1] tracking-wider py-2 px-4 border-2 border-[#404144] whitespace-nowrap rounded-md transition-all duration-300 ease-in-out',
  cross_basis: 'text-2xl cursor-pointer drop-shadow-none hover:drop-shadow-[0_0_2px_#BABABA] transition-all duration-[300ms] ease-in-out',
  members: 'flex flex-row justify-center items-center ml-[1rem]',
  member: 'h-10 w-10 bg-[#313237] border-2 border-[#313237] ml-[-1rem] rounded-full flex justify-center items-center z-20',
  extra_member_text: 'text-[#7d7d80] font-medium text-xs ml-2',
  member_image: 'rounded-full',
  tags_wrapper: 'flex flex-row justify-start items-center gap-x-2.5 w-full',
  tag: 'h-2 w-10 rounded-full'
};